on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'
jobs:
  check-conflict:
    timeout-minutes: 4
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - run: npm install @actions/core
    - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
      id: conflict_pull_requests
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const script = require(`${process.env.GITHUB_WORKSPACE}/cron.js`)
          console.log(script({github, context}))
    - uses: slackapi/slack-github-action@45a88b9581bfab2566dc881e2cd66d334e621e2c # v3.0.3
      with:
        payload: "{\"text\":\"${{ steps.conflict_pull_requests.outputs.value }}\"}"
        webhook-type: webhook-trigger
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
